Repository hackerstribefoundation/nasaspaceapps2020, pull requests merged in 2020-10, with the labels that each got.

#1 Added navigation to individual city directories
  README.md
Labels: bug, enhancement

#2 Localized the README's
  Delhi/README.md
  Gurugram/README.md
  Jodhpur/README.md
  Noida/README.md
Labels: documentation, enhancement

#5 Tech_Army: Astro BackyARd -> NASA Space Apps Challenge 2020
  Delhi/Tech_Army/Images/1601737077115.png
  Delhi/Tech_Army/README-Tech_Army.md
Labels: hacktoberfest, nasaspaceapps-hackerstribe-submission

#6 Uploading Certificate Signing Bot
  certificateSignerBot/.local/AllDependencies.json
  certificateSignerBot/.local/PackageCache.json
  certificateSignerBot/.local/ProjectSettings.json
  certificateSignerBot/.local/certificateSignerBot.nuget.props
  certificateSignerBot/.local/nuget.cache
  certificateSignerBot/.settings/Debug/settings-1a5b880a.json
  certificateSignerBot/.settings/Debug/settings-5190454b.json
  certificateSignerBot/.settings/Debug/settings-590bb27b.json
  certificateSignerBot/.settings/Debug/settings-9e9290da.json
  certificateSignerBot/.settings/Release/settings-1a5b880a.json
  certificateSignerBot/.settings/Release/settings-5190454b.json
  certificateSignerBot/.settings/Release/settings-590bb27b.json
  certificateSignerBot/.settings/Release/settings-9e9290da.json
  certificateSignerBot/Certi_Name_Fill_Participants.xaml
  certificateSignerBot/project.json
Labels: enhancement, hacktoberfest

#7 Added README for CertificateBot
  README.md
  certificateSignerBot/.local/AllDependencies.json
  certificateSignerBot/.local/PackageCache.json
  certificateSignerBot/.local/ProjectSettings.json
  certificateSignerBot/.local/certificateSignerBot.nuget.props
  certificateSignerBot/.local/nuget.cache
  certificateSignerBot/.settings/Debug/settings-1a5b880a.json
  certificateSignerBot/.settings/Debug/settings-5190454b.json
  certificateSignerBot/.settings/Debug/settings-590bb27b.json
  certificateSignerBot/.settings/Debug/settings-9e9290da.json
  certificateSignerBot/.settings/Release/settings-1a5b880a.json
  certificateSignerBot/.settings/Release/settings-5190454b.json
  certificateSignerBot/.settings/Release/settings-590bb27b.json
  certificateSignerBot/.settings/Release/settings-9e9290da.json
  certificateSignerBot/Certi_Name_Fill_Participants.xaml
  certificateSignerBot/project.json
Labels: documentation, hacktoberfest

#8 Adding Generic Template
  CertificateBot/FNAME LNAME.jpg
Labels: good first issue
